//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_LI.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPatient()
        {
            this.tblSickLeaveRequirements = new HashSet<tblSickLeaveRequirement>();
        }
    
        public int patientId { get; set; }
        public string cardNumber { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> doctorId { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSickLeaveRequirement> tblSickLeaveRequirements { get; set; }
    }
}
