//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_LI.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPatient
    {
        public int userId { get; set; }
        public string username { get; set; }
        public string fullname { get; set; }
        public string JMBG { get; set; }
        public string cardNumber { get; set; }
        public Nullable<int> doctorId { get; set; }
    }
}
